package: media_manager_helper
version: '0.0.1-dev'
author: 'KLXM Crossmedia'
supportpage: https://github.com/KLXM/media_manager_helper/
requires:
    redaxo: '^5.18.1'
    php:
        version: '>=8.1, <9'
